version: '3.3'  # version of compose format

services:
  addition:
    build: ./landing/app/add
    ports:
      - 5051:5051 #addition 
    networks:
      sample:
        aliases:
         - add
  subtraction:
    build: ./landing/app/subtract
    ports:
      - 5052:5052 #subtraction
    networks:
      sample:
        aliases:
         - subtract
  multiplication:
    build: ./landing/app/multiplication
    ports:
      - 5053:5053 #multiplication
    networks:
      sample:
        aliases:
         - multiply
  division:
    build: ./landing/app/division
    ports:
      - 5054:5054 #division 
    networks:
      sample:
        aliases:
         - divide
  exponent:
    build: ./landing/app/exponent
    ports:
      - 5055:5055 #exponent
    networks:
      sample:
        aliases:
         - exponent
  lcm:
    build: ./landing/app/lcm
    ports:
      - 5056:5056 #Lowest Common Multiple
    networks:
      sample:
        aliases:
         - lcm
  binomial:
    build: ./landing/app/binomial
    ports:
      - 5057:5057 #Binomial
    networks:
      sample:
        aliases:
         - binomial
  equal:
    build: ./landing/app/equal
    ports:
      - 5058:5058 #equal
    networks:
      sample:
        aliases:
         - equal
  modulus:
    build: ./landing/app/modulus
    ports:
      - 5059:5059 #modulus
    networks:
      sample:
        aliases:
         - modulus
  gcd:
    build: ./landing/app/gcd
    ports:
      - 5060:5060 #gcd
    networks:
      sample:
        aliases:
         - gcd
  gt:
    build: ./landing/app/gt
    ports:
      - 5061:5061 #gt
    networks:
      sample:
        aliases:
         - gt
  lt:
    build: ./landing/app/lt
    ports:
      - 5062:5062 #lt
    networks:
      sample:
        aliases:
         - lt
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  # Add more services below
networks:
  sample:
